# Generated by Django 4.2.9 on 2024-01-31 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.IntegerField(choices=[(1, 'In Progress'), (2, 'Complete'), (3, 'On Hold'), (4, 'Cancelled')], default=1),
        ),
    ]
