# Generated by Django 4.2.9 on 2024-02-02 01:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_alter_company_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='company.company'),
        ),
    ]
