# Generated by Django 4.2.9 on 2024-02-01 16:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_alter_company_name_alter_project_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='project_coordinator',
        ),
        migrations.AddField(
            model_name='project',
            name='project_coordinator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='company.projectcoordinator'),
        ),
    ]
